#!/usr/bin/env python3
"""Read `faults/inventory.toml`: list it, render it, or match it against a log.

The inventory is the machine-readable half of this repo's field notes: failure
modes that each cost hours to find on 8x RTX 5090.  This tool makes them usable
without reading prose:

    python tools/faultscan.py --list                 # the table
    python tools/faultscan.py --show FI-001          # one entry in full
    python tools/faultscan.py server.log             # what went wrong, and the fix
    python tools/faultscan.py --markdown > docs/05-fault-inventory.md

Exit status when scanning: 0 if nothing matched, 1 if a blocker or major fault
matched, 2 if only minor/perf entries matched -- so it drops into CI.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
import tomllib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_INVENTORY = ROOT / "faults" / "inventory.toml"

SEVERITY_ORDER = {"blocker": 0, "major": 1, "minor": 2, "perf": 3}
STATUS_MARK = {
    "open": "open",
    "workaround": "workaround",
    "patch-available": "patch",
    "fixed": "fixed",
    "wontfix": "by design",
}


def load(path: pathlib.Path) -> dict:
    with open(path, "rb") as fh:
        return tomllib.load(fh)


def sort_key(f: dict) -> tuple:
    return (SEVERITY_ORDER.get(f["severity"], 9), f["id"])


def cmd_list(faults: list[dict]) -> int:
    width = max(len(f["id"]) for f in faults)
    print(f"{'ID'.ljust(width)}  {'SEVERITY':<8}  {'STATUS':<11}  {'COMPONENT':<11}  TITLE")
    for f in sorted(faults, key=sort_key):
        print(
            f"{f['id'].ljust(width)}  {f['severity']:<8}  "
            f"{STATUS_MARK.get(f['status'], f['status']):<11}  {f['component']:<11}  {f['title']}"
        )
    return 0


def show(f: dict, *, indent: str = "") -> None:
    print(f"{indent}{f['id']}  [{f['severity']} / {f['status']} / {f['component']}]")
    print(f"{indent}{f['title']}")
    for field in ("symptom", "root_cause", "fix", "evidence"):
        body = f.get(field, "").strip()
        if not body:
            continue
        print(f"\n{indent}--- {field.replace('_', ' ')} ---")
        for line in body.splitlines():
            print(f"{indent}{line}")
    if f.get("references"):
        print(f"\n{indent}see: {', '.join(f['references'])}")


def cmd_show(faults: list[dict], fault_id: str) -> int:
    for f in faults:
        if f["id"].lower() == fault_id.lower():
            show(f)
            return 0
    print(f"no such fault: {fault_id}", file=sys.stderr)
    return 3


def cmd_scan(faults: list[dict], paths: list[str], *, quiet: bool) -> int:
    text = "".join(
        pathlib.Path(p).read_text(errors="replace") if p != "-" else sys.stdin.read()
        for p in paths
    )
    hits = []
    for f in faults:
        matched = [s for s in f.get("signature", []) if re.search(s, text)]
        if matched:
            hits.append((f, matched))

    if not hits:
        print("no known fault signature matched.")
        print("If this is a new failure mode, add it to faults/inventory.toml.")
        return 0

    hits.sort(key=lambda h: sort_key(h[0]))
    print(f"{len(hits)} known fault(s) matched:\n")
    for f, matched in hits:
        print("=" * 78)
        if quiet:
            print(f"{f['id']}  [{f['severity']}]  {f['title']}")
            print(f"  fix: {f['fix'].strip().splitlines()[0]}")
        else:
            print(f"matched: {matched[0]}")
            show(f)
        print()
    worst = min(SEVERITY_ORDER.get(f["severity"], 9) for f, _ in hits)
    return 1 if worst <= 1 else 2


def cmd_markdown(meta: dict, faults: list[dict]) -> int:
    print("# Fault inventory\n")
    print("<!-- generated by tools/faultscan.py --markdown; edit faults/inventory.toml -->\n")
    print(
        f"{len(faults)} failure modes recorded while serving 500 GB-class DeepSeek MoE checkpoints\n"
        "on consumer Blackwell. Each was reproduced here; `evidence` says what was\n"
        "measured rather than inferred.\n"
    )
    print(f"- **Measured on:** {meta['measured_on']}")
    print(f"- **Stack:** {meta['stack']}\n")
    print("`tools/faultscan.py server.log` matches these signatures against a log and")
    print("prints the fix.\n")
    print("| ID | severity | status | component | fault |")
    print("| --- | --- | --- | --- | --- |")
    for f in sorted(faults, key=sort_key):
        anchor = f["id"].lower()
        print(
            f"| [{f['id']}](#{anchor}) | {f['severity']} | "
            f"{STATUS_MARK.get(f['status'], f['status'])} | {f['component']} | {f['title']} |"
        )
    for f in sorted(faults, key=sort_key):
        print(f"\n---\n\n## {f['id']}\n\n### {f['title']}\n")
        print(
            f"**{f['severity']}** · {STATUS_MARK.get(f['status'], f['status'])} · "
            f"`{f['component']}` · affects {', '.join(f['affects'])} on "
            f"{', '.join(f['hardware'])}\n"
        )
        for label, field in (
            ("Symptom", "symptom"),
            ("Root cause", "root_cause"),
            ("Fix", "fix"),
            ("Evidence", "evidence"),
        ):
            body = f.get(field, "").strip()
            if body:
                print(f"**{label}.** {body}\n")
        if f.get("signature"):
            print("**Log signature.**\n")
            print("```")
            for s in f["signature"]:
                print(s)
            print("```\n")
        if f.get("references"):
            print("See " + ", ".join(f"`{r}`" for r in f["references"]) + ".\n")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("logs", nargs="*", help="log files to scan ('-' for stdin)")
    ap.add_argument("--inventory", default=str(DEFAULT_INVENTORY))
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--show", metavar="ID")
    ap.add_argument("--markdown", action="store_true")
    ap.add_argument("-q", "--quiet", action="store_true", help="one line per match")
    args = ap.parse_args()

    data = load(pathlib.Path(args.inventory))
    faults = data["fault"]

    if args.list:
        return cmd_list(faults)
    if args.show:
        return cmd_show(faults, args.show)
    if args.markdown:
        return cmd_markdown(data, faults)
    if args.logs:
        return cmd_scan(faults, args.logs, quiet=args.quiet)
    return cmd_list(faults)


if __name__ == "__main__":
    sys.exit(main())
